param(
    [ValidateSet("setup", "start", "stop", "restart", "status", "logs", "connection", "backup", "restore")]
    [string]$Action = "status",
    [string]$BackupFile = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
Set-Location $projectRoot

$composeFile = Join-Path $projectRoot "deploy\docker\compose.yaml"
$envFile = Join-Path $projectRoot ".env.mongo"
$containerName = "wechat-article-mongodb"
$controlApiContainerName = "wechat-article-control-api"

function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker was not found. Install and start Docker Desktop first."
    }
    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Engine is unavailable. Start Docker Desktop and retry."
    }
}

function New-RandomSecret {
    # Hex-only secrets are strong and do not require MongoDB URI escaping.
    $bytes = New-Object byte[] 32
    $generator = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    }
    finally {
        $generator.Dispose()
    }
    return ([BitConverter]::ToString($bytes) -replace "-", "").ToLowerInvariant()
}

function Read-MongoEnvironment {
    if (-not (Test-Path -LiteralPath $envFile)) {
        throw "Missing .env.mongo. Run: .\mongodb.bat setup"
    }
    $values = @{}
    foreach ($line in Get-Content -LiteralPath $envFile -Encoding UTF8) {
        $value = $line.Trim()
        if (-not $value -or $value.StartsWith("#") -or -not $value.Contains("=")) {
            continue
        }
        $name, $content = $value.Split("=", 2)
        $values[$name.Trim()] = $content.Trim()
    }
    return $values
}

function Assert-EnvironmentReady {
    $values = Read-MongoEnvironment
    if (-not $values["CONTROL_API_TOKEN"] -or $values["CONTROL_API_TOKEN"] -like "*setup*") {
        $generatedToken = New-RandomSecret
        Add-Content -LiteralPath $envFile -Value @(
            "",
            "# Added automatically for the containerized host API.",
            "CONTROL_API_BIND_IP=127.0.0.1",
            "CONTROL_API_PORT=8020",
            "CONTROL_API_TOKEN=$generatedToken"
        ) -Encoding UTF8
        $values = Read-MongoEnvironment
        Write-Host "Added a random CONTROL_API_TOKEN to the existing .env.mongo." -ForegroundColor Yellow
    }
    foreach ($name in @("MONGO_ROOT_USERNAME", "MONGO_ROOT_PASSWORD", "MONGO_APP_USERNAME", "MONGO_APP_PASSWORD", "CONTROL_API_TOKEN")) {
        if (-not $values[$name] -or $values[$name] -like "*setup*") {
            throw "The value $name is missing from .env.mongo. Run setup again."
        }
    }
    return $values
}

function Invoke-Compose {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments)
    & docker compose --env-file $envFile -f $composeFile @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose failed: $($Arguments -join ' ')"
    }
}

function Initialize-Environment {
    if (Test-Path -LiteralPath $envFile) {
        Write-Host ".env.mongo already exists; existing credentials were preserved." -ForegroundColor Yellow
        return
    }
    $rootPassword = New-RandomSecret
    $applicationPassword = New-RandomSecret
    $controlApiToken = New-RandomSecret
    $content = @(
        "# Generated by mongodb.ps1. This file is ignored by Git.",
        "MONGO_BIND_IP=127.0.0.1",
        "MONGO_PORT=27019",
        "MONGO_DATABASE=weixin",
        "MONGO_ROOT_USERNAME=mongo_root",
        "MONGO_ROOT_PASSWORD=$rootPassword",
        "MONGO_APP_USERNAME=wechat_rpa",
        "MONGO_APP_PASSWORD=$applicationPassword",
        "CONTROL_API_BIND_IP=127.0.0.1",
        "CONTROL_API_PORT=8020",
        "CONTROL_API_TOKEN=$controlApiToken"
    )
    Set-Content -LiteralPath $envFile -Value $content -Encoding UTF8
    Write-Host "Created .env.mongo with random credentials." -ForegroundColor Green
}

function Wait-MongoHealthy {
    for ($index = 1; $index -le 30; $index++) {
        $status = (& docker inspect --format "{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}" $containerName 2>$null)
        if ($status -eq "healthy") {
            Write-Host "MongoDB is healthy." -ForegroundColor Green
            return
        }
        if ($status -eq "unhealthy" -or $status -eq "exited") {
            & docker logs --tail 80 $containerName
            throw "MongoDB container entered state: $status"
        }
        Write-Progress -Activity "Starting MongoDB" -Status "State: $status" -PercentComplete (($index / 30) * 100)
        Start-Sleep -Seconds 2
    }
    throw "MongoDB did not become healthy within 60 seconds. Run: .\mongodb.bat logs"
}

function Wait-ControlApiHealthy {
    for ($index = 1; $index -le 30; $index++) {
        $status = (& docker inspect --format "{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}" $controlApiContainerName 2>$null)
        if ($status -eq "healthy") {
            Write-Host "Control API is healthy." -ForegroundColor Green
            return
        }
        if ($status -eq "unhealthy" -or $status -eq "exited") {
            & docker logs --tail 80 $controlApiContainerName
            throw "Control API container entered state: $status"
        }
        Write-Progress -Activity "Starting Control API" -Status "State: $status" -PercentComplete (($index / 30) * 100)
        Start-Sleep -Seconds 2
    }
    throw "Control API did not become healthy within 60 seconds. Run: .\mongodb.bat logs"
}

function Show-Connection {
    $values = Assert-EnvironmentReady
    $hostAddress = if ($values["MONGO_BIND_IP"] -eq "0.0.0.0") { "127.0.0.1" } else { $values["MONGO_BIND_IP"] }
    $uri = "mongodb://" + $values["MONGO_APP_USERNAME"] + ":" + $values["MONGO_APP_PASSWORD"] + "@" + $hostAddress + ":" + $values["MONGO_PORT"] + "/" + $values["MONGO_DATABASE"] + "?authSource=" + $values["MONGO_DATABASE"]
    Write-Host "Application connection settings:" -ForegroundColor Cyan
    Write-Host "MONGO_URI=$uri"
    Write-Host "MONGO_DATABASE=$($values['MONGO_DATABASE'])"
    Write-Host "MONGO_ACCOUNT_COLLECTION=collection_target"
    Write-Host "MONGO_ARTICLE_COLLECTION=article"
    $apiHost = if ($values["CONTROL_API_BIND_IP"] -eq "0.0.0.0") { "127.0.0.1" } else { $values["CONTROL_API_BIND_IP"] }
    Write-Host "CONTROL_API_URL=http://${apiHost}:$($values['CONTROL_API_PORT'])"
}

function Backup-Mongo {
    $values = Assert-EnvironmentReady
    $backupDirectory = Join-Path $projectRoot "output\mongodb-backups"
    New-Item -ItemType Directory -Path $backupDirectory -Force | Out-Null
    $archiveName = "weixin-" + (Get-Date -Format "yyyyMMdd-HHmmss") + ".archive.gz"
    $containerArchive = "/tmp/" + $archiveName
    $localArchive = Join-Path $backupDirectory $archiveName
    $arguments = @(
        "exec", $containerName, "mongodump",
        "--username", $values["MONGO_APP_USERNAME"],
        "--password", $values["MONGO_APP_PASSWORD"],
        "--authenticationDatabase", $values["MONGO_DATABASE"],
        "--db", $values["MONGO_DATABASE"],
        "--archive=$containerArchive", "--gzip"
    )
    & docker @arguments
    if ($LASTEXITCODE -ne 0) { throw "mongodump failed." }
    & docker cp ($containerName + ":" + $containerArchive) $localArchive
    if ($LASTEXITCODE -ne 0) { throw "Could not copy the backup from the container." }
    & docker exec $containerName rm -f $containerArchive
    Write-Host "MongoDB backup created: $localArchive" -ForegroundColor Green
}

function Restore-Mongo {
    if (-not $Force) {
        throw "Restore overwrites matching collections. Retry with -Force after verification."
    }
    if (-not $BackupFile) { throw "Restore requires -BackupFile." }
    $resolvedBackup = (Resolve-Path -LiteralPath $BackupFile).Path
    $values = Assert-EnvironmentReady
    $containerArchive = "/tmp/wechat-article-restore.archive.gz"
    & docker cp $resolvedBackup ($containerName + ":" + $containerArchive)
    if ($LASTEXITCODE -ne 0) { throw "Could not copy the backup into the container." }
    $arguments = @(
        "exec", $containerName, "mongorestore",
        "--username", $values["MONGO_APP_USERNAME"],
        "--password", $values["MONGO_APP_PASSWORD"],
        "--authenticationDatabase", $values["MONGO_DATABASE"],
        "--db", $values["MONGO_DATABASE"],
        "--archive=$containerArchive", "--gzip", "--drop"
    )
    & docker @arguments
    if ($LASTEXITCODE -ne 0) { throw "mongorestore failed." }
    & docker exec $containerName rm -f $containerArchive
    Write-Host "MongoDB restore completed." -ForegroundColor Green
}

Assert-Docker

switch ($Action) {
    "setup" {
        Initialize-Environment
        Assert-EnvironmentReady | Out-Null
        Invoke-Compose config --quiet
        Write-Host "MongoDB configuration is ready. Run: .\mongodb.bat start" -ForegroundColor Green
    }
    "start" {
        Initialize-Environment
        Assert-EnvironmentReady | Out-Null
        Invoke-Compose up -d --build
        Wait-MongoHealthy
        Wait-ControlApiHealthy
        Show-Connection
    }
    "stop" {
        Assert-EnvironmentReady | Out-Null
        Invoke-Compose down
        Write-Host "MongoDB stopped. The data volume was preserved." -ForegroundColor Green
    }
    "restart" {
        Assert-EnvironmentReady | Out-Null
        Invoke-Compose up -d --build
        Wait-MongoHealthy
        Wait-ControlApiHealthy
    }
    "status" {
        Assert-EnvironmentReady | Out-Null
        Invoke-Compose ps
    }
    "logs" {
        Assert-EnvironmentReady | Out-Null
        Invoke-Compose logs --tail 150 mongodb control-api
    }
    "connection" { Show-Connection }
    "backup" { Backup-Mongo }
    "restore" { Restore-Mongo }
}
